Demo.Fagsystem/Pages/Admin.cshtml.cs
using Buf.Meldingsutveksler.SkjemaVerktoy;
using Buf.Meldingsutveksler.SkjemaVerktoy.EnumKodeliste;
using Buf.Meldingsutveksler.SkjemaVerktoy.FilSystem;
using Buf.Meldingsutveksler.SkjemaVerktoy.Tekster;
using Buf.Meldingsutveksler.SkjemaVerktoy.Xml;
using Demo.Fagsystem.Models.FagsystemSimulator.Fagsystem;
using Demo.Fagsystem.Models.Utils;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.IO.Compression;

namespace Demo.Fagsystem.Pages
{
    public class AdminModel() : PageModel
    {

        public void OnGet()
        {
            Init();
        }

        public void OnPost()
        {
            Init();
        }

        private void Init()
        {
            WebUtils.GetRequestParams(Request, out Dictionary<string, string> QueryParams);
            FagsystemBase? instans = FagsystemAccessor.GetFagsystemInstans(QueryParams);
            if (WebUtils.ExistsRequestValue(QueryParams, "deleteAll"))
            {
                try
                {
                    instans?.MeldingStorage.DeleteAll();
                    allDeleted = true;
                    Result = "Alt er slettet";
                }
                catch (Exception ex)
                {
                    Result = "Feilmelding: " + ex.ToString();
                }
            }
            if (WebUtils.ExistsRequestValue(QueryParams, "renewDefs"))
            {
                SkjemaVedrktoyInitializer.Reload();
            }
            if (WebUtils.ExistsRequestValue(QueryParams, "definisjonfil"))
            {
            }
            Error = (XmlSchemaRegister.IsEmptyDefs()) ? "Mangler definisjonsfiler! Last opp her" : "";
        }

        private static MemoryStream FormFileToStream(IFormFile file)
        {
            var stream = new MemoryStream();
            file.CopyTo(stream);
            return stream;
        }

        public void /*async Task<IActionResult>*/ OnPostUploadFiles(List<IFormFile> postedFiles)
        {
            string[] allowedExtensions = [".json", ".xsd"];
            List<string> savedFiles = [];
            List<string> nonSavedFiles = [];
            IFileSystem? fileSystem = SkjemaVedrktoyInitializer.FileSystem
                ?? throw new Exception("Har ikke tilgjengelig filsystem i filopplasting");
            var files = postedFiles;

            var recFile = files.FirstOrDefault(f => f.FileName.Contains(XmlSchemaRegister.FILENAME_REGISTER));
            if (recFile != null)
            {
                var stream = FormFileToStream(recFile);
                fileSystem.Save(recFile.FileName, stream, true);
                savedFiles.Add(recFile.FileName);
            }
            foreach (var file in files)
            {
                if (file != recFile)
                {
                    if (Path.GetExtension(file.FileName).ToLower() == ".zip")
                    {
                        int count = 0;
                        savedFiles.Add("Zip-arkiv med innhold: " + file.FileName);
                        using var stream = FormFileToStream(file);
                        ZipArchive zip = new ZipArchive(stream);
                        foreach (var entry in zip.Entries)
                        {
                            string fileName = entry.ToString().ToLower();
                            if (allowedExtensions.Contains(Path.GetExtension(fileName).ToLower()))
                            {
                                var zipStream = entry.Open();
                                fileSystem.Save(fileName, zipStream, true);
                                savedFiles.Add(fileName);
                                count++;
                            }
                        }
                        savedFiles.Add($"Totalt: {count} filer");
                    }
                    else
                    {
                        if (GetLocation(file, out string directory))
                        {
                            using var stream = FormFileToStream(file);
                            string fileName = directory + "/" + file.FileName;
                            fileSystem.Save(fileName, stream, true);
                            savedFiles.Add(fileName);
                        }
                        else
                            nonSavedFiles.Add(file.FileName);
                    }
                }
            }
            Result = "<b>Lagrede filer:</b><br />" + string.Join("<br />", savedFiles) + "<hr />";
            if (nonSavedFiles.Count > 0)
                Result += "<b>Utelatte filer:</b><br />" + string.Join("<br />", nonSavedFiles) + "<br />";
        }

        private static bool GetLocation(IFormFile file, out string directory)
        {
            directory = "";
            if (Path.GetExtension(file.FileName) == ".xsd")
            {
                var schema = XmlSchemaRegister.Schemas.xsds.FirstOrDefault(x => x.XsdFilnavn == XsdUtils.XSD_DIRECTORY + "/" + file.FileName);
                if (schema != null)
                {
                    directory = XsdUtils.XSD_DIRECTORY;
                    return true;
                }
            }
            else if (file.FileName.Contains(".kodelister."))
            {
                directory = KodelisteUtils.KODELISTER_DIRECTORY;
                return true;
            }
            else if (Path.GetExtension(file.FileName) == ".json")
            {
                var schemaRec = XmlSchemaRegister.Schemas.xsds.FirstOrDefault(x => x.Tekster.Any(t => t.FileName == file.FileName));
                if (schemaRec != null)
                {
                    directory = TeksterUtils.TEKSTER_DIRECTORY;
                    return true;
                }
            }
            return false;
        }

        public bool allDeleted { get; set; } = false;

        public string Result { get; set; } = "";

        public string Error { get; set; } = "";
    }

}

Demo.Fagsystem/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Demo.Fagsystem.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel(Exception ex) : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public Exception Ex { get; set; } = ex;

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

Demo.Fagsystem/Pages/HelloWorld.cshtml.cs
using Demo.Fagsystem.Models.Utils;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Demo.Fagsystem.Pages
{
    public class HelloWorldModel : PageModel
    {
        public string message { get; set; } = "";
        public Dictionary<string, string> QueryParams = [];
        public void OnGet()
        {
            try
            {
                WebUtils.GetRequestParams(Request, out QueryParams);
                string OrgNr = WebUtils.GetRequestValue(QueryParams, Konstanter.Orgnr);
                //var broker = MeldingBrokerAccessor.GetBroker(OrgNr, config, env);
                //                Task result = broker.Store( BlobShareReaderWriter.SaveFileContentsToBlob(config, "test.file", "Hello, world!");
                //                await result;
                message = "OK";
            }
            catch (Exception e)
            {
                message = e.Message + "\n" + e.StackTrace;
            }
        }
    }
}

Demo.Fagsystem/Pages/Index.cshtml.cs
using Buf.Meldingsutveksler.SkjemaVerktoy.Xml;
using Demo.Fagsystem.Models.Business;
using Demo.Fagsystem.Models.FagsystemSimulator.Fagsystem;
using Demo.Fagsystem.Models.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Demo.Fagsystem.Pages
{
    public class IndexModel : PageModel
    {
        public IndexModel()
        {
        }

        public IActionResult OnGet()
        {
            if (XmlSchemaRegister.IsEmptyDefs())
                return Redirect("~/Admin");
            else
                Init();
            return Page();
        }
        public IActionResult OnPost()
        {
            if (XmlSchemaRegister.IsEmptyDefs())
                return Redirect("~/Admin");
            else
                Init();
            return Page();
        }


        public Klient? SelectedKlient { get; set; }

        public FagsystemBase? Instans { get; set; }
        public void Init()
        {
            WebUtils.GetRequestParams(Request, out Dictionary<string, string> queryParams);
            Instans = FagsystemAccessor.GetFagsystemInstans(queryParams);

            string klientId = WebUtils.GetRequestValue(queryParams, Konstanter.SelectedSak);
            if (!string.IsNullOrEmpty(klientId))
                SelectedKlient = Instans?.Klienter.FirstOrDefault(b => b.Id.ToString() == klientId);
        }

    }
}

Demo.Fagsystem/Pages/Issues.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Demo.Fagsystem.Pages
{
    public class IssuesModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Demo.Fagsystem/Pages/LagreMelding.cshtml.cs
using Buf.Meldingsutveksler.SkjemaVerktoy.Xml;
using Buf.Meldingsutveksler.SkjemaVerktoy.Xml.Models;
using Demo.Fagsystem.Models.Demodata;
using Demo.Fagsystem.Models.FagsystemSimulator.Fagsystem;
using Demo.Fagsystem.Models.Utils;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Xml;

namespace Demo.Fagsystem.Pages
{
    public class LagreMeldingModel : PageModel
    {

        public void OnPost()
        {
            Init();
        }

        public void OnGet()
        {
            Init();
        }

        public void Init()
        {
            WebUtils.GetRequestParams(Request, out QueryParams);
            FagsystemBase? instans = FagsystemAccessor.GetFagsystemInstans(QueryParams);
            var storage = instans?.MeldingStorage
                ?? throw new Exception($"Fagsystem '{WebUtils.GetRequestValue(QueryParams, Konstanter.InstansId)}' har ikke gyldig konfigurasjon av meldingslager");
            string existingId = WebUtils.GetRequestValue(QueryParams, Konstanter.XmlId);
            bool meldingExists = existingId != "";
            XmlDocument? doc = null;
            string schemaNmsp;
            if (meldingExists)
            {
                doc = storage.Get(existingId);
                var record = storage.GetRecord(existingId);
                schemaNmsp = record?.Meldingshode?.MeldingstypeNmsp
                    ?? throw new Exception("Meldingshode.MeldingstypeNmsp is NULL");
            }
            else
                schemaNmsp = WebUtils.GetRequestValue(QueryParams, Konstanter.SelectedSkjema);
            var schema = XsdUtils.GetSchema(schemaNmsp);
            var rootElement = XsdUtils.GetRootElement(schema);
            if (QueryParams.ContainsKey(Konstanter.ActionParam))
            {
                Action = WebUtils.GetRequestValue(QueryParams, Konstanter.ActionParam);
            }
            if (!WebUtils.ExistsRequestValue(QueryParams, "Redigert"))
            {
                if (doc != null)
                    XmlFactory.ReadXMLFile(doc, schema, ref QueryParams);
                QueryParams[Konstanter.SelectedSkjema] = schemaNmsp;
            }
            /*var dateTime = */
            DemodataGenerator.Update_SendtTidspunkt(QueryParams, rootElement!.Name!);
            var document = XmlFactory.WriteXml(QueryParams, out Dictionary<string, string> nmsps);

            if (Action == "sendt")
            {
                bool validFormal = XmlValidator.ValidateXmlBuiltIn(document, out string error);
                bool validXtended = XmlValidator.ValidateXml(document, schema, nmsps, Errors);
                if (!(validFormal && validXtended))
                {
                    Action = "lagret";
                    ErrorText = error;
                }
            }
            if (Action == "sendt")
            {
                //broker.Send(document);
            }
            else if (Action == "lagret")
                storage.Store(document);
        }

        public string ErrorText { get; set; } = "";
        public List<XmlValidationError> Errors { get; set; } = [];

        public Dictionary<string, string> QueryParams = [];

        public string FileName { get; set; } = "";

        public string Action { get; set; } = "";

    }
}

Demo.Fagsystem/Pages/Organisasjon.cshtml.cs
using Demo.Fagsystem.Models.FagsystemSimulator.Fagsystem;
using Demo.Fagsystem.Models.Utils;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Xml.Schema;

namespace Demo.Fagsystem.Pages
{
    public class OrganisasjonModel : PageModel
    {
        public void OnGet()
        {
            Init();
        }

        public void OnPost()
        {
            Init();
        }

        public FagsystemBase? Instans { get; set; }

        public XmlSchemaAnnotated? organisasjonElement { get; set; }

        public Dictionary<string, string> QueryParams = [];
        public string? path { get; set; }
        public void Init()
        {
            WebUtils.GetRequestParams(Request, out QueryParams);
            string instansId = WebUtils.GetRequestValue(QueryParams, Konstanter.InstansId);

            Instans = FagsystemAccessor.GetFagsystemInstans(instansId);
            /*path = "Avsender";
            var schema = DataFactory.XsdSchemasWithRootElement.First()
                ?? throw new Exception($"Finner ikke skjema som inneholder '{path}'");
            var element = schema.Items.OfType<XmlSchemaElement>().First();
            barnevernElement = DataFactory.FindByXPath(element, "Avsender").First();*/
        }
    }
}

Demo.Fagsystem/Pages/TestTekster.cshtml.cs
using Demo.Fagsystem.Models.Test;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections;

namespace Demo.Fagsystem.Pages
{
    public class TestTeksterModel : PageModel
    {
        public void OnGet()
        {
            Feil = XsdTester.TestJsonTekster();
        }

        public Dictionary<string, ICollection> Feil { get; set; } = [];
    }
}

Demo.Fagsystem/Pages/Admin.cshtml
@page
@using Demo.Fagsystem
@using Demo.Fagsystem.Models.Utils
@using Demo.Fagsystem.Pages
@using Demo.Fagsystem.Pages.Partial
@model AdminModel
@{
    <h1>Admin-side</h1>
    <hr />
    @if(Model.Error != "")
    {
        <p style="color:red">@Model.Error</p>
        <hr />
    }
    @if (!Model.allDeleted)
    {
        <div>
            <button name="deleteAll">Slett alle meldinger</button><br />
        </div>
    }
    <hr />
    <div>
        <h2>Oppdater definisjoner</h2>
        <p>Last definisjoner på nytt (nødvendig om man har lastet opp nye definisjoner uten å restarte prosess)</p>
        <button name="renewDefs">Bruk oppdaterte definisjoner</button>
    </div>
    <hr />
    <div>
        <h2>Last opp definisjonsfiler:</h2>
        <p>Enkeltfiler i .xsd eller .json - format, evt hele .zip-pakken med definisjoner</p>
        <input type="file" id="postedFiles" name="postedFiles" value="Velg definisjonsfil (.zip eller enkeltfiler)" multiple>

        <button name="filesUpload" id="filesUpload" type="submit" asp-page-handler="UploadFiles">Last opp</button>
    </div>
    <hr />
        <p>@Html.Raw(Model.Result)</p>
    }
}



Demo.Fagsystem/Pages/HelloWorld.cshtml
@page
@using Demo.Fagsystem.Pages
@model HelloWorldModel
@{
    <h1>Hello!</h1>
    <p>@Model.message</p>
}

Demo.Fagsystem/Pages/Index.cshtml
@page
@using Demo.Fagsystem.Pages
@model IndexModel

@await Html.PartialAsync("Partial/Klient.cshtml", Model)

Demo.Fagsystem/Pages/Issues.cshtml
@page
@using Demo.Fagsystem.Pages
@model IssuesModel
@{
    <h1>Om demo-applikasjonen</h1>
    <p>
        <ul>
            <li>Viser hvordan XML-skjemaet (XSD) definert for en melding kan fremstå for bruker</li>
            <li>Demonsterer sending og mottak av meldinger</li>
            <li>Simulerer fagsystem i ulike organisasjoner</li>
        </ul>
    </p>
    <p>
        Visningen av skjema i demoapplikasjonen vil ikke gjenspeile <i>konkret</i> hvordan saksbehandlere i 1.-linje barnevern vil se skjemaene, det styres av leverandører av fagsystemer som brukes.
        Formålet med denne demoapplikasjonen er å teste ut definisjonene, det logiske/informasjonsmessige innholdet og å skape et bilde av den praktiske bruken av definisjonene.
    </p>
    <p>
        For innspill, kontakt gjerne <a href="mailto:bjorge.saether@bufdir.no">Bjørge Sæther</a>
    </p>
    <h1>Mangler</h1>
    <ul>
        <li style="text-decoration:line-through">Sjekk av obligatoriske verdier før lagring</li>
        <li>Visning av hvilke obligatoriske verdier som ikke er satt</li>
        <li>Forvirrende størrelser på overskrifter</li>
        <li style="text-decoration:line-through">Redigering av allerede lagrede meldinger</li>
        <li>Håndtering av ulike versjoner av melding (spesielt meldingshodet)</li>
    </ul>

    <h1>Feil</h1>
    <ul>
        <li style="text-decoration:line-through">Feiler ved forsøk på lagring</li>
    </ul>

    <h1>Videreutvikling</h1>
    <ul>
        <li>Simulere melsingsutveksling mellom 1.- og 2.-linje barnevern <i><b>Under arbeid</b></i></li>
    </ul>

}

Demo.Fagsystem/Pages/LagreMelding.cshtml
@page
@using System.Xml.Schema
@using Buf.Meldingsutveksler.SkjemaVerktoy.Xml
@using Demo.Fagsystem.Pages
@model LagreMeldingModel
@{
    <h3>Melding (@Model.Action)</h3>
    <div>@Model.FileName</div>
    @if (Model.Errors.Count > 0)
    {
        <b>Valideringsfeil: @Model.Errors.Count</b><br/>
        <ul>
            @foreach (var error in Model.Errors)
            {
                string elementName;
                List<XmlSchemaElement> childElements = [];
                if (error.Element == null)
                {
                    elementName = $"Skjema (full systemvalidering)";
                }
                else if (error.Element is XmlSchemaChoice choiceElement)
                {
                    elementName = $"En av feltene [{XsdUtils.GetChoiceElementNames(choiceElement, ", ")}]";
                }
                else
                {
                    elementName = XsdUtils.GetName(error.Element as XmlSchemaAnnotated);
                    childElements = XsdUtils.GetXsdChildElements(error.Element as XmlSchemaAnnotated).Where(el => !XsdUtils.GetIsOptional(el)).Cast<XmlSchemaElement>().ToList();
                }
                <li class="error_li"><div class="error_element">@elementName</div><i>@error.ErrorText</i>
                @if (childElements.Count > 0)
                {
                    <ul>
                    @foreach (var child in childElements)
                    {
                        <li class="error_li_child"><div class="error_element">@XsdUtils.GetName(child)</div><i>Mangler</i></li>
                    }
                    </ul>
                }
                </li>
            }
        </ul>
    }
    <div>
        <button onclick="postForm('/MeldingListe')" >Til liste</button>
    </div>


}

Demo.Fagsystem/Pages/Melding.cshtml
@page
@using System.Xml
@using System.Xml.Schema
@using Buf.Meldingsutveksler.SkjemaVerktoy.Xml
@using Demo.Fagsystem
@using Demo.Fagsystem.Models.ViewModels
@using Demo.Fagsystem.Pages.Partial
@model Demo.Fagsystem.Pages.MeldingModel
@{
    @await Html.PartialAsync("/Pages/Partial/Skjemavelger.cshtml", Model)

    @if (Model.SelectedSchema != null)
    {
        bool disableSend = Model.Fagsystem?.Config.Standalone == "1";
        string disableSendStr = (disableSend) ? "disabled" : "";
        string disableSendToolTip = (disableSend) ? "Applikasjonen er i standalone-modus og kan ikke sende" : "";
        var fileName = Model.SelectedSchema.TargetNamespace;
        var rootElement = XsdUtils.GetRootElement(Model.SelectedSchema)
          ?? throw new Exception($"Skjema {Model.SelectedSchema.TargetNamespace} mangler rotelement");
        @await Html.PartialAsync("/Pages/Partial/XmlElement/Gruppe.cshtml", new PropertyRendererModel(null, Model, "", rootElement))
        <input type="button" name="Send" onclick="postForm('LagreMelding', 'sendt')" value="Send" title="@disableSendToolTip" @disableSendStr />
        <input type="button" name="Lagre" onclick="postForm('LagreMelding', 'lagret')" value="Lagre" />
        <input type="button" name="Avbryt" onclick="postForm('MeldingListe')" value="Avbryt" />
        <input type="hidden" name="@Konstanter.ActionParam" id="@Konstanter.ActionParam" value="">
        <input type="hidden" name="XSD_FIL" id="XSD_FIL" value="@fileName">
        <input type="hidden" name="@Konstanter.XmlId" id="@Konstanter.XmlId" value="@Model.ExistingId">
        <input type="hidden" name="Redigert">
        @if(Model.Message != "")
        {
            @await Html.PartialAsync("/Pages/Partial/MessageOverlay.cshtml", new MessageOverlayModel("Endret Target Namespace for melding", Model.Message));
        }
    }
}

@section Scripts
{
    @foreach (ControlEnabler enabler in Model.controlEnablers)
    {
        <script>
            registerDependentControl('@enabler.EnabledControlId', '@enabler.ControlId', '@enabler.ControlValue', @enabler.IsInverted.ToString().ToLower());
        </script>
    }
    <script>
        setDependentControlsDefault();
    </script>
}

Demo.Fagsystem/Pages/MeldingListe.cshtml
@page
@using System.Xml
@using System.Xml.Schema
@using Buf.Meldingsutveksler.Meldinger.Models
@using Demo.Fagsystem
@using Demo.Fagsystem.Pages
@using Demo.Fagsystem.Pages.Partial
@model MeldingListeModel
@{
//    string processButtonCssClass = (Model.NumPendingTasks > 0) ? "" : "disabled_button";
    <input type="hidden" name="@Konstanter.XmlId" id="@Konstanter.XmlId" value="">
    <input type="hidden" name="@Konstanter.Handling" id="@Konstanter.Handling" value="">
    <input type="hidden" name="@Konstanter.ActionParam" id="@Konstanter.ActionParam" value="">

    <table id="meldingListe" class="melding_liste">
        <thead>
            <tr>
                <th>Type</th>
                <th>Dato / tid</th>
                <th>Id</th>
                <th>Status</th>
                <th>Handling</th>
            </tr>
        </thead>
        @foreach(var melding in Model.Meldinger)
        {

            MeldingMenyModel menyModel = new(melding!);

            string sendtTid = (melding.Meldingshode.SendtTidspunkt != null) ? melding.Meldingshode.SendtTidspunkt/*((DateTime)(melding.Meldingshode.SendtTidspunkt)).ToString("yyyy-MM-dd HH:mm:ss")*/ : "";
            <tr>
                <td>@melding.Meldingshode.Meldingstype<input type="hidden" value="@melding.Meldingshode.Id" name="@melding.Meldingshode.Id" /></td>
                <td>@sendtTid</td>
                <td>@melding.Meldingshode.Id</td>
                <td>@MeldingUtils.GetEnumText(melding.State)</td>
                <td>@await Html.PartialAsync("Partial/MeldingMeny.cshtml", menyModel)</td>
            </tr>
        }
    </table>
    @if (Model.ErrorText != "")
    {
        @await Html.PartialAsync("/Pages/Partial/MessageOverlay.cshtml", new MessageOverlayModel("Feil ved prosessering", Model.ErrorText))
        ;
    }

    <div style="margin-top:20px">
        <button name="refresh" type="submit">Oppfrisk</button>
    </div>
}

Demo.Fagsystem/Pages/Organisasjon.cshtml
@page
@using Demo.Fagsystem.Pages
@model OrganisasjonModel
@{
    <h2>Representert organisasjon</h2>
    @if (Model.Instans != null)
    {
        <div class="variabel"><span class="ledetekst">Navn</span><span class="tekst_verdi">@Model.Instans!.Organisasjon.Navn</span></div>
        <div class="variabel"><span class="ledetekst">Org.nr.</span><span class="tekst_verdi">@Model.Instans.Organisasjon.Organisasjonsnummer</span></div>
        @if (Model.Instans.Organisasjon.Kommuneinfo != null)
        {
            <div class="variabel"><span class="ledetekst">Kommune</span><span class="tekst_verdi">@Model.Instans.Organisasjon.Kommuneinfo.Kommunenummer @Model.Instans.Organisasjon.Kommuneinfo.Kommunenavn</span></div>
            @if(Model.Instans.Organisasjon.Kommuneinfo?.Bydelsinfo != null)
            {
                <div class="variabel"><span class="ledetekst">Bydel</span><span class="tekst_verdi">@Model.Instans.Organisasjon.Kommuneinfo?.Bydelsinfo?.Bydelsnummer @Model.Instans.Organisasjon.Kommuneinfo?.Bydelsinfo?.Bydelsnavn </span></div>
            }
        }
        <h2>Fagsystem</h2>
        <div class="variabel"><span class="ledetekst">Navn</span><span class="tekst_verdi">@Model.Instans!.FagsystemInfo.Navn (v. @Model.Instans!.FagsystemInfo.Versjon)</span></div>
        <div class="variabel"><span class="ledetekst">Produsent</span><span class="tekst_verdi">@Model.Instans.FagsystemInfo.Leverandor</span></div>
    }
    else
    {
        <div class="variabel">(Ikke valgt)</div>
    }
}

Demo.Fagsystem/Pages/TestTekster.cshtml
@page
@using Buf.Meldingsutveksler.SkjemaVerktoy.Tekster.Models
@using Buf.Meldingsutveksler.SkjemaVerktoy.Xml
@using Demo.Fagsystem.Pages
@using System.Xml.Schema
@model TestTeksterModel
@{
    <h2>Test av JSON-tekster:</h2>
    <div>
        <h3>Elementer som ikke er i bruk:</h3>
        @{
            var ikkeBrukte = Model.Feil["ikkeBrukte"];
            if (ikkeBrukte != null)
            {
                foreach (var skjemaelement in ikkeBrukte.Cast<Skjemaelement>())
                {
                    <div>[@skjemaelement.id] @skjemaelement.navn</div>
                }
            }
        }

        <h3>Manglende elementer:</h3>
        @{
            var mangler = Model.Feil["mangler"];
            if (mangler != null)
            {
                foreach (var xsdElement in mangler.Cast<XmlSchemaAnnotated>())
                {
                    <div>[@xsdElement.Id] @XsdUtils.GetName(xsdElement)</div>
                }
            }
        }
    </div>
}